# Shell aliases for tools CLIs (runnable from anywhere)
alias cf-cron='"$HOME/repos/tools/.venv/bin/cf-cron"'
alias docs='"$HOME/repos/tools/.venv/bin/docs"'
alias calendar='"$HOME/repos/tools/.venv/bin/calendar"'
